"""增加文章推荐功能

Revision ID: 3df2a0efbee6
Revises: 9f1b36b7689f
Create Date: 2020-02-22 20:39:33.986210

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3df2a0efbee6'
down_revision = '9f1b36b7689f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recommend', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('is_recommend')

    # ### end Alembic commands ###
